-- Syllabus accountability: a student's own work, read and tagged to the
-- official syllabus dot points, scored into a mastery map that Arcad plans
-- sessions from. See shared/mastery.ts and lib/work-tagging.ts.

-- Official subject matter dot points, shared by every student. Seeded below
-- from shared/syllabus/*.json by scripts/syllabus-seed.mjs.
CREATE TABLE syllabus_points (
  id TEXT PRIMARY KEY,
  syllabus TEXT NOT NULL,
  unit INTEGER NOT NULL,
  unit_title TEXT NOT NULL,
  topic INTEGER NOT NULL,
  topic_title TEXT NOT NULL,
  subtopic TEXT NOT NULL,
  text TEXT NOT NULL,
  -- The sub-topic's teaching hours spread over its dot points.
  hours REAL NOT NULL DEFAULT 1,
  position INTEGER NOT NULL
);
CREATE INDEX syllabus_points_syllabus_idx ON syllabus_points (syllabus, position);

-- Which shared syllabus a student's subject follows, if any.
ALTER TABLE subjects ADD COLUMN syllabus TEXT;

-- One row per piece of work brought in. What was read from it is kept; the
-- file itself only when the student chose to keep it.
CREATE TABLE work_items (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  subject_id TEXT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  -- upload | scan
  source TEXT NOT NULL DEFAULT 'upload',
  filename TEXT NOT NULL,
  content_type TEXT NOT NULL,
  pages INTEGER NOT NULL DEFAULT 1,
  transcript TEXT NOT NULL DEFAULT '',
  -- Set when the student fixed a misread transcript.
  transcript_edited INTEGER NOT NULL DEFAULT 0,
  storage_key TEXT,
  -- read | unread (the model couldn't read it) | checked (check-in done)
  status TEXT NOT NULL DEFAULT 'read',
  prompt_version TEXT NOT NULL,
  model TEXT,
  ms INTEGER,
  created_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000)
);
CREATE INDEX work_items_user_subject_idx ON work_items (user_id, subject_id, created_at);

-- Which dot points a piece of work covered, and how well.
CREATE TABLE work_tags (
  work_item_id TEXT NOT NULL REFERENCES work_items(id) ON DELETE CASCADE,
  point_id TEXT NOT NULL REFERENCES syllabus_points(id),
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- 0-100, from the model's marking. NULL for a tag the student added.
  quality INTEGER,
  questions INTEGER NOT NULL DEFAULT 1,
  evidence TEXT NOT NULL DEFAULT '',
  -- 1-5 from the check-in.
  confidence INTEGER,
  -- ai (not checked yet) | confirmed | removed | added. Removed rows stay,
  -- so corrections can be counted.
  state TEXT NOT NULL DEFAULT 'ai',
  prompt_version TEXT NOT NULL,
  created_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000),
  PRIMARY KEY (work_item_id, point_id)
);
CREATE INDEX work_tags_user_point_idx ON work_tags (user_id, point_id);

-- Real marks, for recalibrating the points they covered.
CREATE TABLE results (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  subject_id TEXT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  assessment_id TEXT REFERENCES subject_assessments(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  mark REAL NOT NULL,
  max_mark REAL NOT NULL,
  taken_on TEXT NOT NULL,
  -- JSON array of syllabus point ids.
  point_ids TEXT NOT NULL DEFAULT '[]',
  created_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000)
);
CREATE INDEX results_user_subject_idx ON results (user_id, subject_id, taken_on);

-- Cached score per point, recomputed when work, a check-in or a mark lands.
CREATE TABLE mastery (
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  point_id TEXT NOT NULL REFERENCES syllabus_points(id),
  score REAL NOT NULL DEFAULT 0,
  q REAL NOT NULL DEFAULT 0,
  c REAL NOT NULL DEFAULT 0,
  r REAL,
  e REAL NOT NULL DEFAULT 0,
  decay REAL NOT NULL DEFAULT 1,
  band TEXT NOT NULL DEFAULT 'none',
  reason TEXT,
  works INTEGER NOT NULL DEFAULT 0,
  last_work_at INTEGER,
  snoozed_until INTEGER,
  covered_elsewhere INTEGER NOT NULL DEFAULT 0,
  updated_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000),
  PRIMARY KEY (user_id, point_id)
);

-- Mathematical Methods: Mathematical Methods 2025 v1.3 General senior syllabus (January 2026), subject matter, Units 1-4
-- © State of Queensland (QCAA) 2026 www.qcaa.qld.edu.au/copyright. Licensed CC BY 4.0. Worked examples trimmed from some dot points.
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.1.1.1', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 1, 'Surds and quadratic functions', 'Surds', 'Understand the concept of a surd as an irrational number represented using a square root or a radical sign.', 1, 0);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.1.1.2', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 1, 'Surds and quadratic functions', 'Surds', 'Simplify square roots of natural numbers which contain perfect square factors.', 1, 1);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.1.1.3', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 1, 'Surds and quadratic functions', 'Surds', 'Rationalise the denominator of fractional expressions involving square roots.', 1, 2);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.1.1.4', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 1, 'Surds and quadratic functions', 'Surds', 'Use the four operations to simplify surds.', 1, 3);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.1.2.1', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 1, 'Surds and quadratic functions', 'Quadratic functions', 'Recognise and determine features of the graphs of y = x², y = ax² + bx + c, y = a(x − h)² + k and y = a(x − x₁)(x − x₂), including their parabolic nature, turning points, axes of symmetry and intercepts.', 1.17, 4);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.1.2.2', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 1, 'Surds and quadratic functions', 'Quadratic functions', 'Solve quadratic equations algebraically using factorisation, the quadratic formula (both exact and approximate solutions), completing the square and using technology.', 1.17, 5);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.1.2.3', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 1, 'Surds and quadratic functions', 'Quadratic functions', 'Sketch the graphs of quadratic functions, with or without technology.', 1.17, 6);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.1.2.4', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 1, 'Surds and quadratic functions', 'Quadratic functions', 'Use the discriminant to determine the number of solutions to a quadratic equation.', 1.17, 7);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.1.2.5', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 1, 'Surds and quadratic functions', 'Quadratic functions', 'Determine turning points and zeros of quadratic functions, with and without technology.', 1.17, 8);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.1.2.6', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 1, 'Surds and quadratic functions', 'Quadratic functions', 'Model and solve problems that involve quadratic functions, with and without technology.', 1.17, 9);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.2.1.1', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 2, 'Binomial expansion and cubic functions', 'Binomial expansion', 'Understand the notion of a combination as an unordered set of r objects taken from a set of n distinct objects.', 1, 10);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.2.1.2', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 2, 'Binomial expansion and cubic functions', 'Binomial expansion', 'Recognise and use the link between Pascal''s triangle and the notation (n r).', 1, 11);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.2.1.3', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 2, 'Binomial expansion and cubic functions', 'Binomial expansion', 'Use the binomial theorem (x + y)ⁿ to expand expressions, e.g. (2x − 1)³.', 1, 12);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.2.2.1', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 2, 'Binomial expansion and cubic functions', 'Cubic functions', 'Identify the coefficients and the degree of a polynomial.', 1.5, 13);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.2.2.2', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 2, 'Binomial expansion and cubic functions', 'Cubic functions', 'Expand quadratic and cubic polynomials from factors.', 1.5, 14);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.2.2.3', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 2, 'Binomial expansion and cubic functions', 'Cubic functions', 'Recognise and determine features of the graphs of y = x³, y = a(x − h)³ + k and y = a(x − x₁)(x − x₂)(x − x₃), including shape, intercepts, and behaviour as x → ∞ and x → −∞.', 1.5, 15);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.2.2.4', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 2, 'Binomial expansion and cubic functions', 'Cubic functions', 'Solve cubic equations using technology, and algebraically in cases where the equation is factorised.', 1.5, 16);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.2.2.5', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 2, 'Binomial expansion and cubic functions', 'Cubic functions', 'Sketch the graphs of cubic functions, with and without technology.', 1.5, 17);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.2.2.6', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 2, 'Binomial expansion and cubic functions', 'Cubic functions', 'Model and solve problems that involve cubic functions, with and without technology.', 1.5, 18);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.3.1.1', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 3, 'Functions and relations', 'Introduction to functions and relations', 'Understand the concept of a relation as a mapping between sets, a graph and as a rule or a formula that defines one variable quantity in terms of another.', 1, 19);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.3.1.2', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 3, 'Functions and relations', 'Introduction to functions and relations', 'Recognise the distinction between functions and relations and use the vertical line test to determine whether a relation is a function.', 1, 20);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.3.1.3', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 3, 'Functions and relations', 'Introduction to functions and relations', 'Recognise and use function notation, domain and range, and independent and dependent variables.', 1, 21);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.3.1.4', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 3, 'Functions and relations', 'Introduction to functions and relations', 'Recognise and use piece-wise functions as a combination of multiple sub-functions with restricted domains.', 1, 22);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.3.1.5', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 3, 'Functions and relations', 'Introduction to functions and relations', 'Model and solve problems that involve piece-wise functions with and without technology.', 1, 23);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.3.2.1', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 3, 'Functions and relations', 'Graphs of relations', 'Recognise and determine features of the graphs of x² + y² = r² and (x − h)² + (y − k)² = r², including their circular shapes, centres and radii.', 0.8, 24);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.3.2.2', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 3, 'Functions and relations', 'Graphs of relations', 'Recognise and determine features of the graph of y² = x, including its parabolic shape and axis of symmetry.', 0.8, 25);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.3.2.3', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 3, 'Functions and relations', 'Graphs of relations', 'Recognise and determine features of the graphs of y = a√(x − h) + k, including their shape, intercepts, and behaviour as x → ∞ and x → −∞.', 0.8, 26);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.3.2.4', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 3, 'Functions and relations', 'Graphs of relations', 'Sketch the graphs of relations, with and without technology.', 0.8, 27);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.3.2.5', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 3, 'Functions and relations', 'Graphs of relations', 'Model and solve problems that involve relations, with and without technology.', 0.8, 28);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.3.3.1', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 3, 'Functions and relations', 'Reciprocal functions', 'Recognise features of the graphs of y = 1/x and y = a/(x − h) + k, including their hyperbolic shape, intercepts, asymptotes, and behaviour as x → ∞ and x → −∞.', 0.67, 29);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.3.3.2', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 3, 'Functions and relations', 'Reciprocal functions', 'Model and solve problems that involve reciprocal functions, with and without technology.', 0.67, 30);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.3.3.3', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 3, 'Functions and relations', 'Reciprocal functions', 'Sketch the graphs of reciprocal functions, with and without technology.', 0.67, 31);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.4.1.1', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 4, 'Trigonometric functions', 'Circular measure and radian measure', 'Define and use radian measure and understand its relationship with degree measure.', 1, 32);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.4.1.2', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 4, 'Trigonometric functions', 'Circular measure and radian measure', 'Calculate lengths of arcs and areas of sectors in circles.', 1, 33);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.4.2.1', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 4, 'Trigonometric functions', 'Introduction to trigonometric functions', 'Understand the unit circle definition of cos(θ), sin(θ) and tan(θ) and periodicity using radians.', 1.14, 34);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.4.2.2', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 4, 'Trigonometric functions', 'Introduction to trigonometric functions', 'Understand and use the exact values of cos(θ), sin(θ) and tan(θ) at integer multiples of π/6 and π/4.', 1.14, 35);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.4.2.3', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 4, 'Trigonometric functions', 'Introduction to trigonometric functions', 'Sketch the graphs of y = sin(x), y = cos(x) and y = tan(x) on extended domains.', 1.14, 36);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.4.2.4', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 4, 'Trigonometric functions', 'Introduction to trigonometric functions', 'Recognise and determine the effect of the parameters a, b, h and k on the graphs of y = a sin(b(x − h)) + k and y = a cos(b(x − h)) + k, with and without technology.', 1.14, 37);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.4.2.5', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 4, 'Trigonometric functions', 'Introduction to trigonometric functions', 'Sketch the graphs of y = a sin(b(x − h)) + k and y = a cos(b(x − h)) + k, with and without technology.', 1.14, 38);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.4.2.6', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 4, 'Trigonometric functions', 'Introduction to trigonometric functions', 'Solve trigonometric equations, with and without technology, including the use of the Pythagorean identity sin²(A) + cos²(A) = 1.', 1.14, 39);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.4.2.7', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 4, 'Trigonometric functions', 'Introduction to trigonometric functions', 'Model and solve problems that involve trigonometric functions, with and without technology.', 1.14, 40);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.5.1.1', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 5, 'Probability', 'Language of events and sets', 'Use the concepts and language of outcomes, sample spaces and events as sets of outcomes.', 1.33, 41);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.5.1.2', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 5, 'Probability', 'Language of events and sets', 'Use set language and notation for events, including A′ for the complement of an event A, A ∩ B for intersection and A ∪ B for union, and recognise mutually exclusive events.', 1.33, 42);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.5.1.3', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 5, 'Probability', 'Language of events and sets', 'Use everyday occurrences to illustrate set descriptions and representations of events, and set operations, including the use of Venn diagrams.', 1.33, 43);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.5.2.1', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 5, 'Probability', 'Conditional probability and independence', 'Use the rules P(A′) = 1 − P(A) and P(A ∪ B) = P(A) + P(B) − P(A ∩ B).', 1, 44);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.5.2.2', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 5, 'Probability', 'Conditional probability and independence', 'Understand the notion of a conditional probability and recognise and use language that indicates conditionality.', 1, 45);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.5.2.3', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 5, 'Probability', 'Conditional probability and independence', 'Use the notation P(A|B) and the formula P(A ∩ B) = P(A|B)P(B) to solve problems.', 1, 46);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.5.2.4', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 5, 'Probability', 'Conditional probability and independence', 'Understand and use the notion of independence of an event A from an event B, as defined by P(A|B) = P(A).', 1, 47);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.5.2.5', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 5, 'Probability', 'Conditional probability and independence', 'Use the formula P(A ∩ B) = P(A)P(B) for independent events A and B.', 1, 48);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.5.2.6', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 5, 'Probability', 'Conditional probability and independence', 'Use relative frequencies obtained from data as point estimates of conditional probabilities and as indications of possible independence of events.', 1, 49);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-1.5.2.7', 'qcaa-methods-2025', 1, 'Surds, algebra, functions and probability', 5, 'Probability', 'Conditional probability and independence', 'Model and solve problems that involve probability, with and without technology.', 1, 50);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.1.1.1', 'qcaa-methods-2025', 2, 'Calculus and further functions', 1, 'Exponential functions', 'Indices and index laws', 'Use indices (including negative and fractional indices) and the index laws.', 1.33, 51);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.1.1.2', 'qcaa-methods-2025', 2, 'Calculus and further functions', 1, 'Exponential functions', 'Indices and index laws', 'Convert radicals to and from fractional indices.', 1.33, 52);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.1.1.3', 'qcaa-methods-2025', 2, 'Calculus and further functions', 1, 'Exponential functions', 'Indices and index laws', 'Understand and use scientific notation.', 1.33, 53);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.1.2.1', 'qcaa-methods-2025', 2, 'Calculus and further functions', 1, 'Exponential functions', 'Introduction to exponential functions', 'Recognise and determine the qualitative features of the graph of y = rˣ (where r > 0), including asymptote and intercept.', 1.2, 54);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.1.2.2', 'qcaa-methods-2025', 2, 'Calculus and further functions', 1, 'Exponential functions', 'Introduction to exponential functions', 'Recognise and determine the effect of the parameters h, k and r on the graph of y = r^(x − h) + k (where r > 0), with and without technology.', 1.2, 55);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.1.2.3', 'qcaa-methods-2025', 2, 'Calculus and further functions', 1, 'Exponential functions', 'Introduction to exponential functions', 'Sketch the graphs of exponential functions, with and without technology.', 1.2, 56);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.1.2.4', 'qcaa-methods-2025', 2, 'Calculus and further functions', 1, 'Exponential functions', 'Introduction to exponential functions', 'Solve equations involving exponential functions, with and without technology.', 1.2, 57);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.1.2.5', 'qcaa-methods-2025', 2, 'Calculus and further functions', 1, 'Exponential functions', 'Introduction to exponential functions', 'Model and solve problems that involve exponential functions, with and without technology.', 1.2, 58);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.2.1.1', 'qcaa-methods-2025', 2, 'Calculus and further functions', 2, 'Logarithms and logarithmic functions', 'Logarithms and logarithmic laws', 'Define logarithms as indices, where aˣ = b is equivalent to x = logₐ(b), and convert between both forms.', 1.67, 59);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.2.1.2', 'qcaa-methods-2025', 2, 'Calculus and further functions', 2, 'Logarithms and logarithmic functions', 'Logarithms and logarithmic laws', 'Use logarithmic laws and definitions, including the product, quotient, power and change-of-base laws, logₐ(a) = 1 and logₐ(1) = 0.', 1.67, 60);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.2.1.3', 'qcaa-methods-2025', 2, 'Calculus and further functions', 2, 'Logarithms and logarithmic functions', 'Logarithms and logarithmic laws', 'Solve equations involving indices using logarithms, with and without technology.', 1.67, 61);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.2.2.1', 'qcaa-methods-2025', 2, 'Calculus and further functions', 2, 'Logarithms and logarithmic functions', 'Logarithmic functions', 'Recognise and determine the qualitative features of the graph of y = logₐ(x) (where a > 1), including asymptote and intercept.', 1.4, 62);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.2.2.2', 'qcaa-methods-2025', 2, 'Calculus and further functions', 2, 'Logarithms and logarithmic functions', 'Logarithmic functions', 'Recognise and determine the effect of the parameters a, h and k on the graph of y = logₐ(x − h) + k (where a > 1), with and without technology.', 1.4, 63);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.2.2.3', 'qcaa-methods-2025', 2, 'Calculus and further functions', 2, 'Logarithms and logarithmic functions', 'Logarithmic functions', 'Sketch graphs of logarithmic functions, with and without technology.', 1.4, 64);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.2.2.4', 'qcaa-methods-2025', 2, 'Calculus and further functions', 2, 'Logarithms and logarithmic functions', 'Logarithmic functions', 'Solve equations involving logarithmic functions with and without technology.', 1.4, 65);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.2.2.5', 'qcaa-methods-2025', 2, 'Calculus and further functions', 2, 'Logarithms and logarithmic functions', 'Logarithmic functions', 'Model and solve problems that involve logarithmic functions, e.g. decibels in acoustics and the Richter scale for earthquake magnitude, with and without technology.', 1.4, 66);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.3.1.1', 'qcaa-methods-2025', 2, 'Calculus and further functions', 3, 'Introduction to differential calculus', 'Rates of change and the concept of derivatives', 'Determine average rate of change in a variety of practical contexts.', 1.25, 67);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.3.1.2', 'qcaa-methods-2025', 2, 'Calculus and further functions', 3, 'Introduction to differential calculus', 'Rates of change and the concept of derivatives', 'Use the rule f′(x) = lim(h→0) (f(x + h) − f(x))/h to determine the derivative of simple power functions and polynomial functions from first principles.', 1.25, 68);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.3.1.3', 'qcaa-methods-2025', 2, 'Calculus and further functions', 3, 'Introduction to differential calculus', 'Rates of change and the concept of derivatives', 'Interpret the derivative as the instantaneous rate of change.', 1.25, 69);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.3.1.4', 'qcaa-methods-2025', 2, 'Calculus and further functions', 3, 'Introduction to differential calculus', 'Rates of change and the concept of derivatives', 'Interpret the derivative as the gradient of a tangent line of the graph of y = f(x).', 1.25, 70);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.3.1.5', 'qcaa-methods-2025', 2, 'Calculus and further functions', 3, 'Introduction to differential calculus', 'Rates of change and the concept of derivatives', 'Use the rule d/dx xⁿ = nxⁿ⁻¹ for positive integers.', 1.25, 71);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.3.1.6', 'qcaa-methods-2025', 2, 'Calculus and further functions', 3, 'Introduction to differential calculus', 'Rates of change and the concept of derivatives', 'Understand the concept of the derivative as a function.', 1.25, 72);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.3.1.7', 'qcaa-methods-2025', 2, 'Calculus and further functions', 3, 'Introduction to differential calculus', 'Rates of change and the concept of derivatives', 'Recognise and use properties of the derivative d/dx (f(x) + g(x)) = d/dx f(x) + d/dx g(x).', 1.25, 73);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.3.1.8', 'qcaa-methods-2025', 2, 'Calculus and further functions', 3, 'Introduction to differential calculus', 'Rates of change and the concept of derivatives', 'Calculate derivatives of power and polynomial functions.', 1.25, 74);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.4.1.1', 'qcaa-methods-2025', 2, 'Calculus and further functions', 4, 'Applications of differential calculus', 'Graphical applications of derivatives', 'Determine instantaneous rates of change.', 2, 75);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.4.1.2', 'qcaa-methods-2025', 2, 'Calculus and further functions', 4, 'Applications of differential calculus', 'Graphical applications of derivatives', 'Determine the equation of a tangent and a normal of the graph of y = f(x).', 2, 76);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.4.1.3', 'qcaa-methods-2025', 2, 'Calculus and further functions', 4, 'Applications of differential calculus', 'Graphical applications of derivatives', 'Construct and interpret displacement-time graphs, with velocity as the slope of the tangent.', 2, 77);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.4.1.4', 'qcaa-methods-2025', 2, 'Calculus and further functions', 4, 'Applications of differential calculus', 'Graphical applications of derivatives', 'Recognise that velocity is the instantaneous rate of change of displacement with respect to time.', 2, 78);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.4.1.5', 'qcaa-methods-2025', 2, 'Calculus and further functions', 4, 'Applications of differential calculus', 'Graphical applications of derivatives', 'Use the first derivative of a function to determine and identify the nature of stationary points.', 2, 79);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.4.1.6', 'qcaa-methods-2025', 2, 'Calculus and further functions', 4, 'Applications of differential calculus', 'Graphical applications of derivatives', 'Sketch curves associated with power functions and polynomials up to degree 4; find stationary points and local and global maxima and minima with and without technology; and examine behaviour as x → ∞ and x → −∞.', 2, 80);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.5.1.1', 'qcaa-methods-2025', 2, 'Calculus and further functions', 5, 'Further differentiation', 'Differentiation rules', 'Use the chain rule to determine the derivative of composite functions involving power and polynomial functions.', 2.75, 81);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.5.1.2', 'qcaa-methods-2025', 2, 'Calculus and further functions', 5, 'Further differentiation', 'Differentiation rules', 'Use the product rule to determine the derivative of products of functions involving power and polynomial functions.', 2.75, 82);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.5.1.3', 'qcaa-methods-2025', 2, 'Calculus and further functions', 5, 'Further differentiation', 'Differentiation rules', 'Use the quotient rule to determine the derivative of quotients of functions involving power and polynomial functions.', 2.75, 83);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-2.5.1.4', 'qcaa-methods-2025', 2, 'Calculus and further functions', 5, 'Further differentiation', 'Differentiation rules', 'Solve problems that involve combinations of the chain rule, product rule and quotient rule to differentiate functions involving power and polynomial functions, expressing derivatives in simplest and factorised form.', 2.75, 84);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.1.1.1', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 1, 'Differentiation of exponential and logarithmic functions', 'Calculus of exponential functions', 'Estimate the limit of (aʰ − 1)/h as h → 0, using technology, for various values of a > 0.', 1.5, 85);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.1.1.2', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 1, 'Differentiation of exponential and logarithmic functions', 'Calculus of exponential functions', 'Recognise that e is the unique number a for which the above limit is 1.', 1.5, 86);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.1.1.3', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 1, 'Differentiation of exponential and logarithmic functions', 'Calculus of exponential functions', 'Recognise and determine the qualitative features of the graph of y = eˣ, including asymptote and intercept.', 1.5, 87);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.1.1.4', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 1, 'Differentiation of exponential and logarithmic functions', 'Calculus of exponential functions', 'Use the rules d/dx eˣ = eˣ and d/dx e^f(x) = f′(x)e^f(x).', 1.5, 88);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.1.2.1', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 1, 'Differentiation of exponential and logarithmic functions', 'Calculus of logarithmic functions', 'Recognise and determine the qualitative features of the graph of y = ln(x) = logₑ(x), including asymptote and intercept.', 1.6, 89);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.1.2.2', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 1, 'Differentiation of exponential and logarithmic functions', 'Calculus of logarithmic functions', 'Recognise and use the inverse relationship of the functions y = eˣ and y = ln(x).', 1.6, 90);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.1.2.3', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 1, 'Differentiation of exponential and logarithmic functions', 'Calculus of logarithmic functions', 'Solve equations involving exponential and logarithmic functions with base e, with and without technology.', 1.6, 91);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.1.2.4', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 1, 'Differentiation of exponential and logarithmic functions', 'Calculus of logarithmic functions', 'Use the rules d/dx ln(x) = 1/x and d/dx ln(f(x)) = f′(x)/f(x).', 1.6, 92);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.1.2.5', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 1, 'Differentiation of exponential and logarithmic functions', 'Calculus of logarithmic functions', 'Model and solve problems that involve derivatives of exponential and logarithmic functions, with and without technology.', 1.6, 93);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.2.1.1', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 2, 'Differentiation of trigonometric functions and differentiation rules', 'Calculus of trigonometric functions', 'Use the rules d/dx sin(x) = cos(x) and d/dx sin(f(x)) = f′(x)cos(f(x)).', 1.67, 94);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.2.1.2', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 2, 'Differentiation of trigonometric functions and differentiation rules', 'Calculus of trigonometric functions', 'Use the rules d/dx cos(x) = −sin(x) and d/dx cos(f(x)) = −f′(x)sin(f(x)).', 1.67, 95);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.2.1.3', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 2, 'Differentiation of trigonometric functions and differentiation rules', 'Calculus of trigonometric functions', 'Model and solve problems that involve derivatives of trigonometric functions, with and without technology.', 1.67, 96);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.2.2.1', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 2, 'Differentiation of trigonometric functions and differentiation rules', 'Differentiation rules', 'Use the chain rule to determine the derivative of composite functions involving exponential, logarithmic and trigonometric functions, expressing derivatives in simplest and factorised form.', 1.25, 97);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.2.2.2', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 2, 'Differentiation of trigonometric functions and differentiation rules', 'Differentiation rules', 'Use the product rule to determine the derivative of exponential, logarithmic and trigonometric functions, expressing derivatives in simplest and factorised form.', 1.25, 98);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.2.2.3', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 2, 'Differentiation of trigonometric functions and differentiation rules', 'Differentiation rules', 'Use the quotient rule to determine the derivative of exponential, logarithmic and trigonometric functions, expressing derivatives in simplest and factorised form.', 1.25, 99);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.2.2.4', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 2, 'Differentiation of trigonometric functions and differentiation rules', 'Differentiation rules', 'Solve problems that involve combinations of the chain rule, product rule and quotient rule to differentiate exponential, logarithmic and trigonometric functions.', 1.25, 100);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.3.1.1', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 3, 'Further applications of differentiation', 'The second derivative and applications of differentiation', 'Understand the concept of the second derivative as the rate of change of the first derivative function.', 1.67, 101);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.3.1.2', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 3, 'Further applications of differentiation', 'The second derivative and applications of differentiation', 'Recognise acceleration as the second derivative of displacement with respect to time.', 1.67, 102);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.3.1.3', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 3, 'Further applications of differentiation', 'The second derivative and applications of differentiation', 'Understand the concepts of concavity and points of inflection and their relationship with the second derivative.', 1.67, 103);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.3.1.4', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 3, 'Further applications of differentiation', 'The second derivative and applications of differentiation', 'Understand and use the second derivative test for finding local maxima and minima.', 1.67, 104);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.3.1.5', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 3, 'Further applications of differentiation', 'The second derivative and applications of differentiation', 'Sketch the graph of a function using first and second derivatives to locate stationary points and points of inflection.', 1.67, 105);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.3.1.6', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 3, 'Further applications of differentiation', 'The second derivative and applications of differentiation', 'Model and solve optimisation problems from a wide variety of fields using first and second derivatives, where the function to be optimised is either given or to be developed.', 1.67, 106);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.4.1.1', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 4, 'Introduction to integration', 'Anti-differentiation', 'Recognise anti-differentiation as the reverse of differentiation.', 0.75, 107);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.4.1.2', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 4, 'Introduction to integration', 'Anti-differentiation', 'Use the notation ∫f(x)dx for anti-derivatives or indefinite integrals.', 0.75, 108);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.4.1.3', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 4, 'Introduction to integration', 'Anti-differentiation', 'Use the formula ∫xⁿdx = xⁿ⁺¹/(n + 1) + c for n ≠ −1.', 0.75, 109);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.4.1.4', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 4, 'Introduction to integration', 'Anti-differentiation', 'Use the formula ∫eˣdx = eˣ + c.', 0.75, 110);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.4.1.5', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 4, 'Introduction to integration', 'Anti-differentiation', 'Use the formula ∫(1/x)dx = ln(x) + c, for x > 0.', 0.75, 111);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.4.1.6', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 4, 'Introduction to integration', 'Anti-differentiation', 'Use the formulas ∫sin(x)dx = −cos(x) + c and ∫cos(x)dx = sin(x) + c.', 0.75, 112);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.4.1.7', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 4, 'Introduction to integration', 'Anti-differentiation', 'Understand and use the formulas ∫(f(x) + g(x))dx = ∫f(x)dx + ∫g(x)dx and ∫kf(x)dx = k∫f(x)dx.', 0.75, 113);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.4.1.8', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 4, 'Introduction to integration', 'Anti-differentiation', 'Determine indefinite integrals of the form ∫f(ax + b)dx.', 0.75, 114);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.4.1.9', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 4, 'Introduction to integration', 'Anti-differentiation', 'Determine f(x) given f′(x) and an initial condition f(a) = b.', 0.75, 115);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.4.1.10', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 4, 'Introduction to integration', 'Anti-differentiation', 'Determine displacement given velocity and the initial value of displacement.', 0.75, 116);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.4.1.11', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 4, 'Introduction to integration', 'Anti-differentiation', 'Determine displacement given acceleration and initial values of displacement and velocity.', 0.75, 117);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.4.1.12', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 4, 'Introduction to integration', 'Anti-differentiation', 'Model and solve problems that involve indefinite integrals, with and without technology.', 0.75, 118);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.5.1.1', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 5, 'Discrete random variables', 'General discrete random variables', 'Understand the concepts of a discrete random variable and its associated probability function, and its use in modelling data.', 0.63, 119);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.5.1.2', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 5, 'Discrete random variables', 'General discrete random variables', 'Use relative frequencies obtained from data to determine point estimates of probabilities associated with a discrete random variable.', 0.63, 120);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.5.1.3', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 5, 'Discrete random variables', 'General discrete random variables', 'Recognise uniform discrete random variables and use them to model random phenomena with equally likely outcomes.', 0.63, 121);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.5.1.4', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 5, 'Discrete random variables', 'General discrete random variables', 'Recognise non-uniform discrete random variables and use them to model random phenomena.', 0.63, 122);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.5.1.5', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 5, 'Discrete random variables', 'General discrete random variables', 'Determine and use the mean (expected value) of a discrete random variable, E(X) = μ = Σpᵢxᵢ, as a measurement of centre.', 0.63, 123);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.5.1.6', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 5, 'Discrete random variables', 'General discrete random variables', 'Determine and use the variance of a discrete random variable, Var(X) = Σpᵢ(xᵢ − μ)², as a measure of spread.', 0.63, 124);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.5.1.7', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 5, 'Discrete random variables', 'General discrete random variables', 'Determine and use the standard deviation of a discrete random variable, √Var(X), as a measure of spread.', 0.63, 125);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.5.1.8', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 5, 'Discrete random variables', 'General discrete random variables', 'Model and solve problems that involve discrete random variables and associated probabilities, with and without technology.', 0.63, 126);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.5.2.1', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 5, 'Discrete random variables', 'Bernoulli distributions', 'Use a Bernoulli random variable as a model for two-outcome situations.', 0.5, 127);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.5.2.2', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 5, 'Discrete random variables', 'Bernoulli distributions', 'Identify contexts suitable for modelling by Bernoulli random variables.', 0.5, 128);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.5.2.3', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 5, 'Discrete random variables', 'Bernoulli distributions', 'Recognise and determine the mean p and variance p(1 − p) of the Bernoulli distribution with parameter p.', 0.5, 129);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.5.2.4', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 5, 'Discrete random variables', 'Bernoulli distributions', 'Model and solve problems that involve Bernoulli random variables and associated probabilities, with and without technology.', 0.5, 130);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.5.3.1', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 5, 'Discrete random variables', 'Binomial distributions', 'Understand the concepts of Bernoulli trials and the concept of a binomial random variable as the number of ''successes'', r, in n independent Bernoulli trials, with the same probability of success p in each trial.', 0.83, 131);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.5.3.2', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 5, 'Discrete random variables', 'Binomial distributions', 'Identify contexts suitable for modelling by binomial random variables.', 0.83, 132);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.5.3.3', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 5, 'Discrete random variables', 'Binomial distributions', 'Determine and use the probabilities P(X = r) = (n r)pʳ(1 − p)ⁿ⁻ʳ associated with the binomial distribution with parameters n and p.', 0.83, 133);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.5.3.4', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 5, 'Discrete random variables', 'Binomial distributions', 'Calculate the mean np and variance np(1 − p) of a binomial distribution using technology and algebraic methods.', 0.83, 134);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.5.3.5', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 5, 'Discrete random variables', 'Binomial distributions', 'Use the language of probability, including at most, at least, no more than, no less than, inclusive and between.', 0.83, 135);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-3.5.3.6', 'qcaa-methods-2025', 3, 'Further calculus and introduction to statistics', 5, 'Discrete random variables', 'Binomial distributions', 'Model and solve problems that involve binomial distributions and associated probabilities with and without technology.', 0.83, 136);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.1.1.1', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 1, 'Further integration', 'Fundamental theorem of calculus and definite integrals', 'Use sums of the form Σf(xᵢ)δxᵢ to estimate the area under the curve y = f(x).', 0.75, 137);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.1.1.2', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 1, 'Further integration', 'Fundamental theorem of calculus and definite integrals', 'Recognise the definite integral ∫ₐᵇf(x)dx as a limit of sums of the form Σf(xᵢ)δxᵢ.', 0.75, 138);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.1.1.3', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 1, 'Further integration', 'Fundamental theorem of calculus and definite integrals', 'Understand the fundamental theorem of calculus, ∫ₐᵇf(x)dx = F(b) − F(a), and use it to calculate definite integrals.', 0.75, 139);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.1.1.4', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 1, 'Further integration', 'Fundamental theorem of calculus and definite integrals', 'Use the definite integral ∫ₐᵇf(x)dx to determine the area under the curve y = f(x) between x = a and x = b if f(x) > 0 over this interval.', 0.75, 140);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.1.2.1', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 1, 'Further integration', 'Applications of integration', 'Calculate the area enclosed by a curve and the x-axis over a given domain, with and without technology.', 1.6, 141);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.1.2.2', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 1, 'Further integration', 'Applications of integration', 'Calculate the area between curves, with and without technology.', 1.6, 142);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.1.2.3', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 1, 'Further integration', 'Applications of integration', 'Use the trapezoidal rule to approximate an area and the value of a definite integral, with and without technology.', 1.6, 143);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.1.2.4', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 1, 'Further integration', 'Applications of integration', 'Calculate total change by integrating instantaneous or marginal rates of change, with and without technology.', 1.6, 144);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.1.2.5', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 1, 'Further integration', 'Applications of integration', 'Model and solve problems that involve definite integrals, including motion problems, with and without technology.', 1.6, 145);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.2.1.1', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 2, 'Trigonometry', 'Cosine and sine rules', 'Use the sine rule (ambiguous case is required), a/sin(A) = b/sin(B) = c/sin(C).', 2.5, 146);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.2.1.2', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 2, 'Trigonometry', 'Cosine and sine rules', 'Use the cosine rule, c² = a² + b² − 2ab cos(C).', 2.5, 147);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.2.1.3', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 2, 'Trigonometry', 'Cosine and sine rules', 'Use the formula area = ½bc sin(A) to calculate the area of a triangle.', 2.5, 148);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.2.1.4', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 2, 'Trigonometry', 'Cosine and sine rules', 'Model and solve problems that involve the sine rule, cosine rule and the area formula in two- and three-dimensional contexts (including bearings, directions and angles of elevation and depression), with and without technology.', 2.5, 149);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.3.1.1', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 3, 'Continuous random variables and the normal distribution', 'General continuous random variables', 'Use relative frequencies and histograms obtained from data to estimate probabilities associated with a continuous random variable.', 1.2, 150);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.3.1.2', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 3, 'Continuous random variables and the normal distribution', 'General continuous random variables', 'Understand the concepts of a probability density function, cumulative distribution function, and probabilities associated with a continuous random variable given by integrals; examine simple types of continuous random variables and use them in appropriate contexts.', 1.2, 151);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.3.1.3', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 3, 'Continuous random variables and the normal distribution', 'General continuous random variables', 'Calculate the expected value, E(X) = μ = ∫xp(x)dx, of a continuous random variable where p(x) is the probability density function.', 1.2, 152);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.3.1.4', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 3, 'Continuous random variables and the normal distribution', 'General continuous random variables', 'Calculate the variance, Var(X) = σ² = ∫(x − μ)²p(x)dx, and standard deviation σ, of a continuous random variable.', 1.2, 153);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.3.1.5', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 3, 'Continuous random variables and the normal distribution', 'General continuous random variables', 'Understand standardised normal variables (z-values, z-scores) and use these to compare samples.', 1.2, 154);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.3.2.1', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 3, 'Continuous random variables and the normal distribution', 'Normal distributions', 'Identify contexts, e.g. naturally occurring variations, that are suitable for modelling by normal random variables.', 1.2, 155);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.3.2.2', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 3, 'Continuous random variables and the normal distribution', 'Normal distributions', 'Recognise features of the graph of the probability density function of the normal distribution with mean μ and standard deviation σ and the use of the standard normal distribution.', 1.2, 156);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.3.2.3', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 3, 'Continuous random variables and the normal distribution', 'Normal distributions', 'Recognise and use the link between the normal distribution and the notation X ∼ N(μ, σ²).', 1.2, 157);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.3.2.4', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 3, 'Continuous random variables and the normal distribution', 'Normal distributions', 'Calculate probabilities and quantiles associated with a given normal distribution, using technology.', 1.2, 158);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.3.2.5', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 3, 'Continuous random variables and the normal distribution', 'Normal distributions', 'Model and solve problems that involve normal distributions, with and without technology.', 1.2, 159);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.4.1.1', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 4, 'Sampling and proportions', 'Random sampling', 'Understand the concept of a random sample.', 0.75, 160);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.4.1.2', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 4, 'Sampling and proportions', 'Random sampling', 'Understand sources of bias in samples, and procedures to ensure randomness.', 0.75, 161);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.4.1.3', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 4, 'Sampling and proportions', 'Random sampling', 'Identify and use procedures to ensure randomness.', 0.75, 162);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.4.1.4', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 4, 'Sampling and proportions', 'Random sampling', 'Recognise and use graphical displays of real and simulated data of random samples from various types of distributions, including uniform, Bernoulli, binomial and normal.', 0.75, 163);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.4.2.1', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 4, 'Sampling and proportions', 'Sample proportions', 'Understand the concept of the sample proportion p̂ as a random variable whose value varies between samples, and the formulas for the mean p and standard deviation √(p(1 − p)/n) of the sample proportion p̂.', 2.67, 164);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.4.2.2', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 4, 'Sampling and proportions', 'Sample proportions', 'Recognise and use the approximate normality of the distribution of p̂ for large samples.', 2.67, 165);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.4.2.3', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 4, 'Sampling and proportions', 'Sample proportions', 'Use repeated random sampling data, for a variety of values of p and a range of sample sizes, to examine the distribution of p̂ and the approximate standard normality of (p̂ − p)/√(p̂(1 − p̂)/n), where the closeness of the approximation depends on both n and p.', 2.67, 166);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.5.1.1', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 5, 'Interval estimates for proportions', 'Confidence intervals for proportions', 'Understand the concept of an interval estimate for a parameter associated with a random variable.', 1.83, 167);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.5.1.2', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 5, 'Interval estimates for proportions', 'Confidence intervals for proportions', 'Understand and use the approximate confidence interval p̂ ± z√(p̂(1 − p̂)/n) as an interval estimate for p, the population proportion, where z is the appropriate quantile for the standard normal distribution.', 1.83, 168);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.5.1.3', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 5, 'Interval estimates for proportions', 'Confidence intervals for proportions', 'Understand and use the approximate margin of error, z√(p̂(1 − p̂)/n).', 1.83, 169);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.5.1.4', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 5, 'Interval estimates for proportions', 'Confidence intervals for proportions', 'Understand and use the relationship between margin of error, level of confidence and sample size.', 1.83, 170);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.5.1.5', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 5, 'Interval estimates for proportions', 'Confidence intervals for proportions', 'Understand that there are variations in confidence intervals between samples and that most, but not all, confidence intervals contain p.', 1.83, 171);
INSERT OR REPLACE INTO syllabus_points (id, syllabus, unit, unit_title, topic, topic_title, subtopic, text, hours, position) VALUES ('MM-4.5.1.6', 'qcaa-methods-2025', 4, 'Further calculus, trigonometry and statistics', 5, 'Interval estimates for proportions', 'Confidence intervals for proportions', 'Model and solve problems that involve interval estimates for proportions, with and without technology.', 1.83, 172);
